// YKS konu müfredatı — Konu Takibi modülünün omurgası.
//
// ⚠️ Bu liste ÖSYM'nin resmî müfredat metni DEĞİLDİR; yaygın kaynak/kurum
// müfredatlarına göre derlenmiştir. Ders ekleme/çıkarma gerekirse buradan
// düzenlenir — topic_progress kayıtları (subject_key, topic) çiftiyle eşleştiği
// için bir konunun ADI değişirse o konunun geçmiş kaydı eşleşmez.
// Konu adını değiştirmek yerine yenisini eklemek daha güvenlidir.

export type ExamGroup = "TYT" | "AYT";

export interface CurriculumSubject {
  key: string;
  label: string;
  group: ExamGroup;
  icon: string;
  topics: string[];
}

export const CURRICULUM: CurriculumSubject[] = [
  {
    key: "tyt-turkce",
    label: "Türkçe",
    group: "TYT",
    icon: "📖",
    topics: [
      "Sözcükte Anlam",
      "Deyim ve Atasözü",
      "Cümlede Anlam",
      "Paragrafta Anlam",
      "Paragrafta Yapı",
      "Paragrafta Konu ve Ana Düşünce",
      "Paragrafta Yardımcı Düşünce",
      "Anlatım Biçimleri",
      "Ses Bilgisi",
      "Yazım Kuralları",
      "Noktalama İşaretleri",
      "Sözcükte Yapı",
      "İsimler",
      "Sıfatlar",
      "Zamirler",
      "Zarflar",
      "Edat, Bağlaç ve Ünlem",
      "Fiiller",
      "Fiilimsiler",
      "Fiilde Çatı",
      "Cümlenin Ögeleri",
      "Cümle Türleri",
      "Anlatım Bozuklukları",
    ],
  },
  {
    key: "tyt-matematik",
    label: "Temel Matematik",
    group: "TYT",
    icon: "🔢",
    topics: [
      "Temel Kavramlar",
      "Sayı Basamakları",
      "Bölme ve Bölünebilme",
      "EBOB - EKOK",
      "Rasyonel Sayılar",
      "Basit Eşitsizlikler",
      "Mutlak Değer",
      "Üslü Sayılar",
      "Köklü Sayılar",
      "Çarpanlara Ayırma",
      "Oran - Orantı",
      "Denklem Çözme",
      "Sayı Problemleri",
      "Kesir Problemleri",
      "Yaş Problemleri",
      "İşçi ve Havuz Problemleri",
      "Hareket ve Hız Problemleri",
      "Yüzde Problemleri",
      "Kâr - Zarar Problemleri",
      "Karışım Problemleri",
      "Grafik Problemleri",
      "Kümeler",
      "Kartezyen Çarpım",
      "Mantık",
      "Fonksiyonlar",
      "Polinomlar",
      "İkinci Dereceden Denklemler",
      "Permütasyon",
      "Kombinasyon",
      "Olasılık",
      "Veri ve İstatistik",
    ],
  },
  {
    key: "tyt-geometri",
    label: "Geometri",
    group: "TYT",
    icon: "📐",
    topics: [
      "Doğruda Açılar",
      "Üçgende Açılar",
      "Özel Üçgenler",
      "Dik Üçgen ve Öklid Bağıntıları",
      "İkizkenar ve Eşkenar Üçgen",
      "Üçgende Alan",
      "Üçgende Benzerlik",
      "Açıortay ve Kenarortay",
      "Çokgenler",
      "Dörtgenler",
      "Paralelkenar",
      "Eşkenar Dörtgen ve Yamuk",
      "Çember ve Daire",
      "Analitik Geometri",
      "Katı Cisimler",
    ],
  },
  {
    key: "tyt-fizik",
    label: "Fizik",
    group: "TYT",
    icon: "⚡",
    topics: [
      "Fizik Bilimine Giriş",
      "Madde ve Özellikleri",
      "Sıvıların Kaldırma Kuvveti",
      "Basınç",
      "Isı, Sıcaklık ve Genleşme",
      "Hareket ve Kuvvet",
      "Newton'un Hareket Yasaları",
      "İş, Güç ve Enerji",
      "Elektrostatik",
      "Elektrik Akımı ve Devreler",
      "Mıknatıs ve Manyetik Alan",
      "Dalgalar",
      "Optik",
    ],
  },
  {
    key: "tyt-kimya",
    label: "Kimya",
    group: "TYT",
    icon: "🧪",
    topics: [
      "Kimya Bilimi",
      "Atom ve Periyodik Sistem",
      "Kimyasal Türler Arası Etkileşimler",
      "Maddenin Halleri",
      "Kimyanın Temel Kanunları",
      "Mol Kavramı",
      "Kimyasal Hesaplamalar",
      "Karışımlar",
      "Asit, Baz ve Tuz",
      "Doğa ve Kimya",
      "Kimya Her Yerde",
    ],
  },
  {
    key: "tyt-biyoloji",
    label: "Biyoloji",
    group: "TYT",
    icon: "🧬",
    topics: [
      "Canlıların Ortak Özellikleri",
      "Canlıların Temel Bileşenleri",
      "Hücre ve Organeller",
      "Hücre Zarından Madde Geçişi",
      "Canlıların Sınıflandırılması",
      "Mitoz ve Eşeysiz Üreme",
      "Mayoz ve Eşeyli Üreme",
      "Kalıtım",
      "Ekosistem Ekolojisi",
      "Güncel Çevre Sorunları",
    ],
  },
  {
    key: "tyt-tarih",
    label: "Tarih",
    group: "TYT",
    icon: "🏛️",
    topics: [
      "Tarih ve Zaman",
      "İnsanlığın İlk Dönemleri",
      "Orta Çağ'da Dünya",
      "İlk ve Orta Çağlarda Türk Dünyası",
      "İslam Medeniyetinin Doğuşu",
      "Türklerin İslamiyet'i Kabulü",
      "Yerleşme ve Devletleşme",
      "Beylikten Devlete Osmanlı",
      "Dünya Gücü Osmanlı",
      "Osmanlı'da Değişim",
      "Milli Mücadele",
      "Atatürkçülük ve İnkılaplar",
    ],
  },
  {
    key: "tyt-cografya",
    label: "Coğrafya",
    group: "TYT",
    icon: "🌍",
    topics: [
      "Doğa ve İnsan",
      "Dünya'nın Şekli ve Hareketleri",
      "Coğrafi Konum",
      "Harita Bilgisi",
      "İklim Bilgisi",
      "Yerin Şekillenmesi",
      "Nüfus",
      "Göç",
      "Yerleşme",
      "Ekonomik Faaliyetler",
      "Bölgeler",
      "Doğal Afetler",
    ],
  },
  {
    key: "tyt-felsefe",
    label: "Felsefe",
    group: "TYT",
    icon: "💭",
    topics: [
      "Felsefeyi Tanıma",
      "Bilgi Felsefesi",
      "Varlık Felsefesi",
      "Ahlak Felsefesi",
      "Sanat Felsefesi",
      "Din Felsefesi",
      "Siyaset Felsefesi",
      "Bilim Felsefesi",
    ],
  },
  {
    key: "tyt-din",
    label: "Din Kültürü",
    group: "TYT",
    icon: "🕌",
    topics: [
      "Bilgi ve İnanç",
      "Din ve İslam",
      "İslam ve İbadet",
      "Ahlak ve Değerler",
      "Allah - İnsan İlişkisi",
      "Hz. Muhammed ve Gençlik",
      "Vahiy ve Akıl",
    ],
  },

  /* ── AYT ── */
  {
    key: "ayt-matematik",
    label: "Matematik",
    group: "AYT",
    icon: "🔢",
    topics: [
      "Fonksiyonlar (İleri)",
      "Polinomlar",
      "İkinci Dereceden Denklemler",
      "Eşitsizlikler",
      "Parabol",
      "Trigonometri",
      "Logaritma",
      "Diziler",
      "Limit ve Süreklilik",
      "Türev",
      "Türev Uygulamaları",
      "İntegral",
      "İntegral Uygulamaları",
      "Permütasyon - Kombinasyon",
      "Olasılık (İleri)",
      "Binom Açılımı",
      "Karmaşık Sayılar",
      "Matris ve Determinant",
      "Lineer Denklem Sistemleri",
    ],
  },
  {
    key: "ayt-geometri",
    label: "Geometri",
    group: "AYT",
    icon: "📐",
    topics: [
      "Analitik Geometri - Doğru",
      "Analitik Geometri - Çember",
      "Dönüşüm Geometrisi",
      "Katı Cisimler - Prizmalar",
      "Piramit, Koni ve Küre",
      "Vektörler",
      "Trigonometri Uygulamaları",
      "Çemberde Açı ve Uzunluk",
      "Dörtgenlerde İleri Konular",
    ],
  },
  {
    key: "ayt-fizik",
    label: "Fizik",
    group: "AYT",
    icon: "⚡",
    topics: [
      "Vektörler",
      "Bağıl Hareket",
      "Newton'un Hareket Yasaları",
      "Atışlar",
      "İtme ve Momentum",
      "Tork ve Denge",
      "Basit Makineler",
      "Elektriksel Kuvvet ve Alan",
      "Paralel Levhalar ve Sığa",
      "Manyetizma ve İndüksiyon",
      "Alternatif Akım",
      "Transformatörler",
      "Çembersel Hareket",
      "Basit Harmonik Hareket",
      "Dalga Mekaniği",
      "Atom Fiziği",
      "Radyoaktivite",
      "Modern Fizik",
    ],
  },
  {
    key: "ayt-kimya",
    label: "Kimya",
    group: "AYT",
    icon: "🧪",
    topics: [
      "Modern Atom Teorisi",
      "Gazlar",
      "Sıvı Çözeltiler",
      "Çözünürlük",
      "Kimyasal Tepkimelerde Enerji",
      "Kimyasal Tepkimelerde Hız",
      "Kimyasal Denge",
      "Asit - Baz Dengesi",
      "Çözünürlük Dengesi",
      "Kimya ve Elektrik",
      "Karbon Kimyasına Giriş",
      "Organik Bileşikler",
      "Enerji Kaynakları",
    ],
  },
  {
    key: "ayt-biyoloji",
    label: "Biyoloji",
    group: "AYT",
    icon: "🧬",
    topics: [
      "Sinir Sistemi",
      "Endokrin Sistem",
      "Duyu Organları",
      "Destek ve Hareket Sistemi",
      "Sindirim Sistemi",
      "Dolaşım ve Bağışıklık Sistemi",
      "Solunum Sistemi",
      "Üriner Sistem",
      "Üreme Sistemi ve Embriyonik Gelişim",
      "Komünite ve Popülasyon Ekolojisi",
      "Nükleik Asitler",
      "Genetik Şifre ve Protein Sentezi",
      "Fotosentez",
      "Hücresel Solunum",
      "Bitki Biyolojisi",
    ],
  },
  {
    key: "ayt-edebiyat",
    label: "Edebiyat",
    group: "AYT",
    icon: "📚",
    topics: [
      "Güzel Sanatlar ve Edebiyat",
      "Metinlerin Sınıflandırılması",
      "Şiir Bilgisi",
      "Ölçü, Uyak ve Redif",
      "Söz Sanatları",
      "İslamiyet Öncesi Türk Edebiyatı",
      "Geçiş Dönemi Eserleri",
      "Halk Edebiyatı",
      "Divan Edebiyatı",
      "Tanzimat Edebiyatı",
      "Servet-i Fünun Edebiyatı",
      "Fecr-i Ati Edebiyatı",
      "Milli Edebiyat",
      "Cumhuriyet Dönemi Şiir",
      "Cumhuriyet Dönemi Roman ve Hikâye",
      "Edebi Akımlar",
      "Dünya Edebiyatı",
      "Tiyatro",
    ],
  },
  {
    key: "ayt-tarih",
    label: "Tarih",
    group: "AYT",
    icon: "🏛️",
    topics: [
      "İlk Türk Devletleri",
      "Türk - İslam Devletleri",
      "Osmanlı Kuruluş Dönemi",
      "Osmanlı Yükselme Dönemi",
      "Osmanlı Duraklama Dönemi",
      "Osmanlı Gerileme ve Dağılma",
      "XX. Yüzyıl Başlarında Osmanlı",
      "I. Dünya Savaşı",
      "Milli Mücadele Hazırlık Dönemi",
      "Kurtuluş Savaşı Cepheleri",
      "Lozan Antlaşması",
      "Atatürk İnkılapları",
      "Atatürk Dönemi Dış Politika",
      "II. Dünya Savaşı ve Sonrası",
      "Soğuk Savaş Dönemi",
      "Çağdaş Türk ve Dünya Tarihi",
    ],
  },
  {
    key: "ayt-cografya",
    label: "Coğrafya",
    group: "AYT",
    icon: "🌍",
    topics: [
      "Ekosistem ve Madde Döngüleri",
      "Biyoçeşitlilik",
      "Nüfus Politikaları",
      "Şehirleşme",
      "Ekonomik Faaliyetler ve Doğal Kaynaklar",
      "Türkiye'de Tarım",
      "Türkiye'de Hayvancılık",
      "Türkiye'de Madenler ve Enerji",
      "Türkiye'de Sanayi",
      "Türkiye'de Ulaşım, Ticaret ve Turizm",
      "Bölgesel Kalkınma Projeleri",
      "Küresel Ortam: Bölgeler ve Ülkeler",
      "Doğal Afetler ve Risk Yönetimi",
      "Çevre Sorunları",
    ],
  },
  {
    key: "ayt-felsefe",
    label: "Felsefe Grubu",
    group: "AYT",
    icon: "💭",
    topics: [
      "İlk Çağ Felsefesi",
      "MÖ 6 - MS 2 Felsefesi",
      "MS 2 - MS 15 Felsefesi",
      "15. - 17. Yüzyıl Felsefesi",
      "18. - 19. Yüzyıl Felsefesi",
      "20. Yüzyıl Felsefesi",
      "Psikolojiye Giriş",
      "Öğrenme ve Bellek",
      "Sosyolojiye Giriş",
      "Toplumsal Yapı",
      "Mantığa Giriş",
      "Klasik Mantık",
      "Sembolik Mantık",
    ],
  },
  {
    key: "ayt-din",
    label: "DKAB",
    group: "AYT",
    icon: "🕌",
    topics: [
      "Dünya ve Ahiret",
      "Kur'an'a Göre Hz. Muhammed",
      "Kur'an'da Bazı Kavramlar",
      "İnançla İlgili Meseleler",
      "Yahudilik ve Hıristiyanlık",
      "İslam Düşüncesinde Yorumlar",
    ],
  },
];

export const TOPIC_STATUSES = [
  { key: "baslanmadi", label: "Başlanmadı", color: "#94a3b8", bg: "#f1f5f9" },
  { key: "devam", label: "Devam Ediyor", color: "#E2600F", bg: "#fff7ed" },
  { key: "bitti", label: "Bitti", color: "#059669", bg: "#ecfdf5" },
  { key: "tekrar", label: "Tekrar Gerekli", color: "#dc2626", bg: "#fef2f2" },
] as const;

export type TopicStatus = (typeof TOPIC_STATUSES)[number]["key"];

export function statusMeta(key: string) {
  return TOPIC_STATUSES.find((s) => s.key === key) ?? TOPIC_STATUSES[0];
}

export const TOTAL_TOPIC_COUNT = CURRICULUM.reduce((n, s) => n + s.topics.length, 0);
